import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const heroImg='https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85';
const opImg='https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=85';
const scaleImg='https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85';

function Modal({type,onClose}){const [sent,setSent]=useState(false); if(!type)return null; return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}>{!sent?<><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">{type==='call'?'STRATEGY CALL':'STR SCALING CHECKLIST'}</span><h3>{type==='call'?'Let’s talk about the next stage of your portfolio.':'Get the operator checklist.'}</h3><p>{type==='call'?'A focused 20–30 minute conversation about your current operation, bottlenecks and growth plans.':'A practical checklist covering the systems operators need as they move beyond a handful of units.'}</p>{type==='call'?<div className="form-grid"><input placeholder="Name"/><input placeholder="Work email"/><input placeholder="Current units"/><input placeholder="Location"/><button className="button dark full" onClick={()=>setSent(true)}>Continue to booking →</button></div>:<div className="form-grid"><input placeholder="Name"/><input placeholder="Email"/><button className="button dark full" onClick={()=>setSent(true)}>Send me the checklist →</button></div>}</>:<><span className="eyebrow">YOU’RE IN</span><h3>{type==='call'?'Next step: choose a time.':'Checklist requested.'}</h3><p>{type==='call'?'Your details are captured. In production, this step connects to the calendar booking flow.':'In production, the checklist would be delivered to your inbox.'}</p><button className="button dark" onClick={onClose}>Done</button></>}</div></div>}

function App(){const [modal,setModal]=useState(null); const [open,setOpen]=useState(null);
const faqs=[['Who is Flex Academy for?','It is designed primarily for STR operators already managing properties who want to build repeatable systems and grow beyond an owner-operator setup.'],['Is this a course?','No. The programme is built around implementation, operator decisions, systems and direct guidance rather than a library of passive video lessons.'],['Do I need to manage 30 units already?','No. The intended audience is operators in the 5–30 unit range who are ready to build the next layer of their business.'],['What happens on the strategy call?','You discuss your current portfolio, operating bottlenecks, growth goals and whether the programme is a fit.']];

return <><header className="nav"><a className="logo" href="#">FLEX<span>ACADEMY</span></a><nav><a href="#method">Method</a><a href="#programme">Programme</a><a href="#founders">Founders</a><a href="#faq">FAQ</a></nav><button className="button dark small" onClick={()=>setModal('call')}>Book a strategy call</button></header>
<main>
<section className="hero"><div className="hero-copy"><span className="eyebrow">FLEX ACADEMY · FOR STR OPERATORS</span><h1>From STR operator<br/><em>to STR company.</em></h1><p>Build the systems, deals and operating playbook behind a real multi-city STR business — with guidance from the founders who built The Flex.</p><div className="actions"><button className="button dark" onClick={()=>setModal('call')}>Book a free strategy call <span>↗</span></button><button className="button light" onClick={()=>setModal('checklist')}>Get the STR Scaling Checklist</button></div><small>Built from the operating playbook behind The Flex + Base360.</small></div><div className="hero-media"><img src={heroImg}/><div className="dashboard"><div className="dash-top"><span>PORTFOLIO OVERVIEW</span><b>LIVE</b></div><div className="dash-number">18 <small>active units</small></div><div className="dash-stats"><div><b>91.4%</b><span>Occupancy</span></div><div><b>£142</b><span>RevPAR</span></div><div><b>07</b><span>Open tasks</span></div></div><div className="chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div></section>

<section className="proof"><div>THE FLEX</div><span>Real-world STR operation</span><i></i><div>BASE360</div><span>Technology + systems</span><i></i><div>FLEX ACADEMY</div><span>The transferable operator playbook</span></div>

<section className="problem section"><div className="section-head"><span className="eyebrow">THE PROBLEM</span><h2>3 units feels like a side hustle.<br/><em>30 units feels like a company.</em></h2><p>The gap isn’t motivation. It’s the operating system between the two.</p></div><div className="cards four">{[['01','Manual operations','Every new property creates another set of tasks, exceptions and messages.'],['02','Thin margins','Without disciplined systems, growth can add workload faster than profit.'],['03','No repeatable system','What works in one property doesn’t automatically become a company process.'],['04','Growth bottleneck','The operator becomes the person every decision still has to pass through.']].map(x=><article className="card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>

<section id="method" className="method section dark-section"><div className="section-head"><span className="eyebrow">THE FLEX PLAYBOOK</span><h2>A playbook built from<br/><em>operating, not theorising.</em></h2><p>Five stages that turn scattered activity into a repeatable operating model.</p></div><div className="steps">{[['01','Source','Find the right properties and structure the right deals.'],['02','Launch','Get properties live with repeatable setup systems.'],['03','Operate','Build SOPs for guests, cleaning, maintenance and teams.'],['04','Optimise','Use pricing, data and systems to improve performance.'],['05','Scale','Build the people and processes for the next stage.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>

<section className="operations section"><div className="image-card"><img src={opImg}/><div className="ops-ui"><div><span>PROPERTIES</span><b>18</b></div><div><span>TEAM TASKS</span><b>42</b></div><div><span>EXCEPTIONS</span><b>03</b></div></div></div><div className="content"><span className="eyebrow">SYSTEMS OVER SCALE</span><h2>Stop running every property as a one-off.</h2><p>At scale, the goal isn’t to work harder. It’s to make the right work repeatable — so people, processes and technology can carry more of the operation.</p><ul><li>Clear SOPs and ownership</li><li>Exception-based management</li><li>Repeatable launch processes</li><li>Decision-making with better data</li></ul></div></section>

<section id="founders" className="ecosystem section"><div className="section-head"><span className="eyebrow">THE ECOSYSTEM</span><h2>Real operation. Real systems.<br/><em>Transferable playbook.</em></h2></div><div className="eco-grid"><div className="eco-photo"><img src={scaleImg}/><div className="photo-label">A portfolio that operates like a company.</div></div><div className="eco-stack"><article><span>01</span><h3>THE FLEX</h3><p>Real-world short-term rental operation — where the playbook is tested.</p></article><article><span>02</span><h3>BASE360</h3><p>Technology and systems that help operators manage complexity at scale.</p></article><article className="active"><span>03</span><h3>FLEX ACADEMY</h3><p>The operator programme built to transfer the thinking, systems and decisions behind the operation.</p></article></div></div><div className="founder-note"><span className="eyebrow">FOUNDER-LED</span><h3>Learn directly from the people behind the operation.</h3><p>Raouf Yousfi and Michael Buggy bring the Academy to life through operator context, decisions and practical feedback.</p></div></section>

<section id="programme" className="programme section"><div className="section-head"><span className="eyebrow">THE PROGRAMME</span><h2>12 weeks to build<br/><em>your operating layer.</em></h2></div><div className="programme-grid"><div className="programme-number">12<span>WEEKS</span></div><div className="programme-list"><div><b>01</b><span>Weekly group sessions</span></div><div><b>02</b><span>Monthly founder 1:1</span></div><div><b>03</b><span>Operator community</span></div><div><b>04</b><span>Templates + SOPs</span></div><div><b>05</b><span>Base360 access</span></div></div></div></section>

<section className="qualification section"><div className="qual yes"><span className="eyebrow">THIS IS FOR YOU IF</span><h2>You’re ready to build a real business.</h2><ul><li>You already operate STR properties.</li><li>You want repeatable systems, not more theory.</li><li>You’re willing to implement and be challenged.</li><li>You want to grow beyond yourself.</li></ul></div><div className="qual no"><span className="eyebrow">NOT FOR YOU IF</span><h2>You’re looking for passive income.</h2><ul><li>You haven’t launched an STR yet.</li><li>You only want recorded videos.</li><li>You expect someone else to operate the business.</li><li>You want shortcuts without implementation.</li></ul></div></section>

<section className="results section"><div className="section-head"><span className="eyebrow">OPERATOR RESULTS</span><h2>Proof should come from<br/><em>the work.</em></h2><p>Real case studies belong here — with the operator, starting point, challenge and measured outcome clearly shown.</p></div><div className="case-grid">{[['CASE STUDY 01','[Operator / Company]','Starting point: [X] units','Outcome: [Measured result]'],['CASE STUDY 02','[Operator / Company]','Challenge: [Operational challenge]','Outcome: [Measured result]']].map(x=><article className="case" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><strong>{x[3]}</strong></article>)}</div></section>

<section id="faq" className="faq section"><div className="section-head"><span className="eyebrow">FAQ</span><h2>Before you book.</h2></div><div className="faq-list">{faqs.map((f,i)=><div className="faq-item" key={f[0]}><button onClick={()=>setOpen(open===i?null:i)}><span>{f[0]}</span><b>{open===i?'−':'+'}</b></button>{open===i&&<p>{f[1]}</p>}</div>)}</div></section>

<section className="final-cta"><div><span className="eyebrow">NEXT STAGE</span><h2>Build the next stage<br/><em>of your STR business.</em></h2><p>Bring your current portfolio, your bottlenecks and your growth plans. We’ll talk through what comes next.</p><div className="actions"><button className="button light" onClick={()=>setModal('call')}>Book a free strategy call ↗</button><button className="button outline-light" onClick={()=>setModal('checklist')}>Get the scaling checklist</button></div><small>20–30 minute conversation · No obligation.</small></div></section>
</main><footer><div className="logo">FLEX<span>ACADEMY</span></div><span>For STR operators ready to build the company behind the portfolio.</span><span>© 2026 Flex Academy</span></footer><Modal type={modal} onClose={()=>setModal(null)}/></>}

createRoot(document.getElementById('root')).render(<App/>);